# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
