# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awewards', '0002_auto_20190321_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
